### ISSUE TITLE
Add table datadog_host

### ISSUE THREAD

**Issue by thom-vend** [turbot/steampipe-plugin-datadog#19]
Hi there,
First thank you for this nice plugin!

Here a suggestion to add a table: to get the list of hosts (infrastructure_hosts)

Have a nice day,

**References**
https://docs.datadoghq.com/developers/guide/query-the-infrastructure-list-via-the-api/

**Comment by marcus-crane** [comment]
I've got a version of a `datadog_host` table running locally that should be ready shortly to submit 🙂

**Comment by cbruno10** [comment]
Hey @thom-vend , thanks for the kind words, hopefully the plugin has proved useful for you so far!

@marcus-crane Thanks for taking up this table, looking forward to trying out your new table and reviewing the PR when it's ready.

**Comment by marcus-crane** [comment]
I've tidied up the table and opened a PR for review 🙂

**Comment by marcus-crane** [comment]
I'll try to address the review shortly 🙂
